version: 2
updates:
- package-ecosystem: npm
  directory: "/alphabot"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: mongoose
    versions:
    - 5.11.15
    - 5.11.20
    - 5.12.0
    - 5.12.2
    - 5.12.5
  - dependency-name: tmi.js
    versions:
    - 1.7.4
    - 1.8.0
    - 1.8.1
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
